parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: shop
    database_user: root
    database_password: ~
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: pl
    secret: ThisTokenIsNotSoSecretChangeIt
    facebook.client.id: ClientIdChangeIt
    facebook.client.secret: ClientSecretChangeIt
