app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    defaults:  { _locale: pl }
    requirements:
        _locale: |pl|en
    
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
